### PR TITLE
Gets ssr up and running

### PR DESCRIPTION
**Pull request by mikesol**
It's good to get SSR set up early on as you iterate on the project. Eventually, as it's a blog, it'll output multiple pages, but here, it's just outputting `index.html`. You can check out how it's done in `webpack.config.js` & then use `view-source` in your browser to see it in action!

### CODE REVIEW

**Comment by MonoidMusician** [comment]
Things look fine on the ssr side, but `[ text_ "(", text_ "L", text_ ")" ]` gets clobbered during hydration, only the last text node gets rendered, so I just see `)` for example 😞 `runInBody` still works fine on its own

**Comment by mikesol** [comment]
I think this may be fixed now with a new version of Deku - when you get the chance, could you look at the output & see if it's 100% what you're expecting?

**Comment by MonoidMusician** [comment]
It's better! But now the value of the last child gets copied into the first child, so I see `)L)` rendered now :joy:

**Comment by mikesol** [comment]
Ok, thanks for your attention to detail! I didn't spot that but now I see it & I have my work cut out for me :)

**Comment by mikesol** [comment]
Fixed with the newest Deku (I had forgotten to change a variable in one JS file...d'oh!).
Screen Shot 2022-06-16 at 11 20 03 AM

**Pull request merged**
